name: dependabot-pr-post-processing

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write # to commit
  pull-requests: write # to label PRs

jobs:
  metadata:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    outputs:
      dependency-names: ${{ steps.metadata.outputs.dependency-names }}
      dependency-group: ${{ steps.metadata.outputs.dependency-group }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  internal-deps:
    needs: metadata
    if: needs.metadata.outputs.dependency-group == 'infra-gradle' || needs.metadata.outputs.dependency-group == 'test-dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: Add the 'internal' label and enable auto-merge for internal deps
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$PR_URL" --add-label "internal"
          gh pr merge "$PR_URL" --auto --rebase

  update-locks:
    needs: metadata
    # Example dependencies we want to trigger on:
    #   org.jetbrains.kotlin.jvm
    #   org.jetbrains.kotlin.multiplatform
    #   org.jetbrains.kotlin.plugin.serialization
    #   org.jetbrains.kotlin:kotlinx-atomicfu-runtime
    # It's ok to trigger on more dependencies than we want, it just will not result in any
    # lock file changes, and be a no-op.
    if: contains(needs.metadata.outputs.dependency-names, 'org.jetbrains.kotlin')
    runs-on: ubuntu-latest
    steps:
      - name: List dependencies
        run: |
          echo "Dependencies that triggered this job: ${{ needs.metadata.outputs.dependency-names }}"

      - name: Checkout PR branch
        uses: actions/checkout@v7
        with:
          # Important: checkout the PR head, not merge commit
          ref: ${{ github.event.pull_request.head.ref }}
          # Needed so we can push
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Update Kotlin JS/Wasm lock files
        run: |
          ./gradlew kotlinUpgradeYarnLock kotlinWasmUpgradeYarnLock

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add kotlin-js-store
            git commit -m "Update yarn lock files after Kotlin bump"
            git push
          else
            echo "No changes to commit"
          fi
