name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version (and git tag)"
        required: true
      doPublish:
        type: boolean
        description: "Publish to maven (if unchecked, only the changelog, GitHub release, and git tag are done)"
        required: true
        default: true

run-name: "Release ${{ inputs.version }}"

permissions:
  contents: read

jobs:
  release:
    runs-on: macos-latest # For darwin publications
    strategy:
      matrix:
        jdk-version: [ 17 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk-version }}

      - name: Cache Kotlin/Native binaries
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: konan-${{ runner.os }}

      - name: Release
        uses: joffrey-bion/gradle-library-release-action@v2
        with:
          version: ${{ inputs.version }}
          gpg-signing-key: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          gpg-signing-password: ${{ secrets.GPG_PASSWORD }}
          sonatype-username: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          sonatype-password: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
          gradle-publish-tasks: ${{ inputs.doPublish && 'publishAndReleaseToMavenCentral' || '' }}
